/**
 * PaginationBar generates a standard widget that is generally
 * seen when browsing a large number for rows within a table grid.
 * In this case each row represents a Sample Ballot generated by
 * BallotGen software.
 * 
 *  Notes:
 *  - Usually there are usually 231 docx files (or rows in this case)
 */

package com.rodini.ballotcomparator.view;

import java.io.IOException;
import java.util.function.Consumer;

import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Label;

import com.rodini.ballotcomparator.model.BallotDocx;
import com.rodini.ballotcomparator.model.InitializeData;

public class PaginationBar extends Composite {

    private int currentPage = 1;
    private int totalPages = 1;

    private Button btnFirst;
    private Button btnPrev;
    private Button btnNext;
    private Button btnLast;
    private Label lblPageInfo;
//    private Button btnEdit;
    // Default listener.
    private Consumer<Integer> onPageChange = page -> {InitializeData.bdocx.setIndex(page);};

    public PaginationBar(Composite parent, int style) {
        super(parent, style);
        createControls();
        updateControls();
    }

    private void createControls() {
    	setLayout(new GridLayout(1, false));
        // Outer composite that will have two children
        Composite outer = new Composite(this, SWT.NONE);
        GridData outerData = new GridData(SWT.FILL, SWT.CENTER, true, true);
        outer.setLayoutData(outerData);
        // Outer layout (3 columns)
        GridLayout outerLayout = new GridLayout(3, false);
        outerLayout.marginWidth = 0;
        outerLayout.marginHeight = 0;
        outer.setLayout(outerLayout);
        // Spacer
        Label spacer = new Label(outer, SWT.NONE);
        spacer.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false));
        
        // Inner composite that will be centered
        Composite inner = new Composite(outer, SWT.NONE);
        GridData innerData = new GridData(SWT.CENTER, SWT.CENTER, true, false);
        inner.setLayoutData(innerData);

        GridLayout layout = new GridLayout(5, false);
        layout.marginWidth = 0;
        layout.marginHeight = 0;
        layout.horizontalSpacing = 12;
        inner.setLayout(layout);

        btnFirst = new Button(inner, SWT.PUSH);
        btnFirst.setText("⏮ First");
        btnFirst.addListener(SWT.Selection, e -> goToPage(1));

        btnPrev = new Button(inner, SWT.PUSH);
        btnPrev.setText("◀ Prev");
        btnPrev.addListener(SWT.Selection, e -> goToPage(currentPage - 1));

        lblPageInfo = new Label(inner, SWT.NONE);
        lblPageInfo.setLayoutData(new GridData(SWT.CENTER, SWT.CENTER, true, false));

        btnNext = new Button(inner, SWT.PUSH);
        btnNext.setText("Next ▶");
        btnNext.addListener(SWT.Selection, e -> goToPage(currentPage + 1));

        btnLast = new Button(inner, SWT.PUSH);
        btnLast.setText("Last ⏭");
        btnLast.addListener(SWT.Selection, e -> goToPage(totalPages));
        
        // Edit composite that will be right justified.
        Composite edit = new Composite(outer, SWT.NONE);
        GridData editData = new GridData(SWT.RIGHT, SWT.CENTER, true, false);
        edit.setLayoutData(editData);
        GridLayout editLayout = new GridLayout(1, false);
        editLayout.marginWidth = 0;
        editLayout.marginHeight = 0;
        editLayout.horizontalSpacing = 12;
        edit.setLayout(editLayout); 
        Button btnEdit = new Button(edit, SWT.PUSH);
        btnEdit.setText("Edit");
        btnEdit.addListener(SWT.Selection, e -> editDoc(currentPage));
    }

    private void updateControls() {
        lblPageInfo.setText("Page " + currentPage + " of " + totalPages);

        btnFirst.setEnabled(currentPage > 1);
        btnPrev.setEnabled(currentPage > 1);
        btnNext.setEnabled(currentPage < totalPages);
        btnLast.setEnabled(currentPage < totalPages);

        layout(true, true);
    }

    private void goToPage(int page) {
        int newPage = Math.max(1, Math.min(page, totalPages));
        if (newPage != currentPage) {
            currentPage = newPage;
            updateControls();
            onPageChange.accept(currentPage);
        }
    }

    private void editDoc(int page) {    	
    	System.out.printf("Edit docx w/ index: %d%n", page);
    	String docxFilePath = InitializeData.bdocx.getFilePath();
    	// Launch word as separate process using file association with .docx.     
    	ProcessBuilder pb = new ProcessBuilder("cmd.exe", "/c", "start", "\"\"", docxFilePath);
    	try {
			pb.start();
		} catch (IOException e) {
			System.out.printf("MS Word launch failed: %s%n", e.getMessage());
		}
    }
    // ---------------------------
    // Public API
    // ---------------------------

    public void setTotalPages(int totalPages) {
        this.totalPages = Math.max(1, totalPages);
        if (currentPage > this.totalPages) {
            currentPage = this.totalPages;
        }
        updateControls();
    }

    public void setCurrentPage(int page) {
        goToPage(page);
    }

    public int getCurrentPage() {
        return currentPage;
    }

    public int getTotalPages() {
        return totalPages;
    }

    public void setOnPageChange(Consumer<Integer> listener) {
    	// set real listener here.
        this.onPageChange = listener != null ? listener : page -> {};
    }
}